import type { Locale } from "./dict";

const msTranslations: Record<string, string> = {
  "Booking search": "Carian tempahan", "Check Booking": "Semak Tempahan",
  "Enter the phone number used for booking and verify one OTP to view all your match tickets and season passes.": "Masukkan nombor telefon yang digunakan untuk tempahan dan sahkan satu OTP untuk melihat semua tiket perlawanan serta pas musim anda.",
  "Club Management": "Pengurusan Kelab", "The executive committee and advisors of Pattani FC": "Jawatankuasa eksekutif dan penasihat Pattani FC", people: "orang",
  "Players & Staff": "Pemain & Staf", "Pattani FC first-team players and coaching staff": "Pemain pasukan utama dan staf kejurulatihan Pattani FC", players: "pemain", "No player information is available": "Maklumat pemain belum tersedia", "Coaching Staff": "Staf Kejurulatihan",
  Shop: "Kedai", "Official Pattani FC jerseys, apparel, and merchandise": "Jersi, pakaian dan barangan rasmi Pattani FC", Total: "Jumlah", items: "barangan", "No products are available right now": "Tiada produk tersedia buat masa ini", "Please check back again soon": "Sila kunjungi kami semula tidak lama lagi", Sale: "Promosi", Size: "Saiz", "Out of stock": "Kehabisan stok", Remaining: "Baki",
  News: "Berita", "The latest news and updates from Pattani FC": "Berita dan perkembangan terkini Pattani FC", "No news has been published yet": "Belum ada berita diterbitkan", "Date not specified": "Tarikh tidak dinyatakan", "Read more": "Baca selanjutnya",
  "Journey With Us": "Bersama Dalam Perjalanan", Club: "Kelab", Partners: "Rakan Kongsi", "Total Partners": "Jumlah Rakan Kongsi", "Main Sponsors": "Penaja Utama", "Current Season": "Musim Semasa", "No sponsor information is available": "Maklumat penaja belum tersedia", "Become a Partner": "Jadi Rakan Kongsi", "Join Pattani FC on the Journey to Success": "Sertai perjalanan kejayaan Pattani FC", "Contact Partnerships Team": "Hubungi Pasukan Kerjasama",
  "Thank you to every sponsor and partner standing alongside Pattani FC on our journey through Thai football.": "Terima kasih kepada semua penaja dan rakan kongsi yang bersama Pattani FC dalam perjalanan bola sepak Thailand.", "Sponsorship opportunities are available at every level, with packages tailored to your business.": "Peluang penajaan tersedia pada setiap peringkat dengan pakej yang disesuaikan untuk perniagaan anda.",
  "Season Tickets": "Tiket Musim", "One season pass for every home match, with exclusive member benefits": "Satu pas musim untuk semua perlawanan di tempat sendiri, dengan manfaat eksklusif ahli", "Stadium Map": "Pelan Stadium", "Review seating zones before choosing your membership package": "Semak zon tempat duduk sebelum memilih pakej keahlian", "Season Membership": "Keahlian Musim", "Choose Your Membership Package": "Pilih Pakej Keahlian Anda", "One purchase · Watch all": "Satu pembelian · Saksikan semua", "home matches this season": "perlawanan di tempat sendiri musim ini", "THB / season": "THB / musim", matches: "perlawanan", "Membership card preview": "Pratonton kad keahlian", "Available zones:": "Zon tersedia:", "Buy Season Membership": "Beli Keahlian Musim",
  "Match Tickets": "Tiket Perlawanan", "Choose your seating zone — each area of Rainbow Stadium offers a different atmosphere, price, and view": "Pilih zon tempat duduk anda — setiap kawasan Rainbow Stadium menawarkan suasana, harga dan pemandangan yang berbeza", "Book now": "Tempah sekarang", "Matches on Sale": "Perlawanan Dibuka untuk Tempahan", "Choose a match and book your tickets now": "Pilih perlawanan dan tempah tiket anda sekarang", "Seating Zones": "Zon Tempat Duduk", "Choose Your Seating Zone": "Pilih Zon Tempat Duduk Anda", "Review the stadium view, then choose a zone below": "Semak pandangan stadium, kemudian pilih zon di bawah", "Zone colors match the stadium plan above — select a zone to choose a match": "Warna zon sepadan dengan pelan stadium di atas — pilih zon untuk memilih perlawanan", "Choose zone": "Pilih zon", THB: "THB", "How to Book": "Cara Menempah", "Choose a match from the fixtures": "Pilih perlawanan daripada jadual", "Enter your details and ticket quantity (up to 10 per booking)": "Masukkan maklumat dan jumlah tiket anda (maksimum 10 setiap tempahan)", "Pay via PromptPay, Mobile Banking, or Credit Card": "Bayar melalui PromptPay, Perbankan Mudah Alih atau Kad Kredit", "Receive your E-Ticket and show its QR code at the stadium entrance": "Terima E-Tiket dan tunjukkan kod QR di pintu masuk stadium", "View Fixtures": "Lihat Jadual", Zone: "Zon", "Not on sale yet": "Belum dijual", seats: "tempat duduk", of: "daripada", " · shared quota": " · kuota dikongsi",
  "Rainbow Stadium · Pattani — Capacity 10,700 · Tickets THB 100–200": "Rainbow Stadium · Pattani — Kapasiti 10,700 · Tiket THB 100–200", "Rainbow Stadium seating plan — Pattani FC (capacity 10,700)": "Pelan tempat duduk Rainbow Stadium — Pattani FC (kapasiti 10,700)", "* Standard prices may vary by match or opponent. Seat selection opens in the next step.": "* Harga standard mungkin berbeza mengikut perlawanan atau lawan. Pemilihan tempat duduk dibuka pada langkah seterusnya.",
  Results: "Keputusan", "Match results and standings": "Keputusan perlawanan dan kedudukan", "Competition type": "Jenis pertandingan", League: "Liga", Cup: "Piala", Standings: "Kedudukan", "Match Results": "Keputusan Perlawanan", "No results available yet": "Belum ada keputusan", "Match result": "Keputusan perlawanan", Pos: "Ked.", Team: "Pasukan", P: "M", W: "M", D: "S", L: "K", GF: "J", GA: "B", Pts: "Mata", "Qualification / Relegation": "Kelayakan / Penyingkiran",
  "Ranks 1–2 qualify for AFC competition": "Kedudukan 1–2 layak ke pertandingan AFC", "Ranks 3–6 enter the playoffs": "Kedudukan 3–6 memasuki play-off", "Ranks 14–16 are relegated": "Kedudukan 14–16 diturunkan liga", "Standings will appear after match results are recorded": "Kedudukan akan dipaparkan selepas keputusan perlawanan direkodkan",
  "Contact Us": "Hubungi Kami", "Have a question? Contact our team through the channels below.": "Ada pertanyaan? Hubungi pasukan kami melalui saluran di bawah.", Email: "E-mel", Phone: "Telefon", "Office Hours": "Waktu Operasi", "Monday–Saturday, 09:00–18:00": "Isnin–Sabtu, 09:00–18:00", Location: "Lokasi", Pattani: "Pattani", "Follow Pattani FC": "Ikuti Pattani FC", "Contact us and follow the latest club updates through the channels above.": "Hubungi kami dan ikuti perkembangan terkini kelab melalui saluran di atas.",
  Fixtures: "Jadual Perlawanan", "Choose a match to book tickets": "Pilih perlawanan untuk menempah tiket", " — Selected zone: ": " — Zon dipilih: ", "All Fixtures": "Semua Perlawanan", "On Sale": "Dijual", Upcoming: "Akan Datang", All: "Semua", Show: "Papar", "No matches found in this category": "Tiada perlawanan dalam kategori ini", "To be confirmed": "Belum ditetapkan", "Venue to be confirmed": "Lokasi belum ditetapkan", "Prices vary by zone": "Harga berbeza mengikut zon", "Book Tickets": "Tempah Tiket", "View Details": "Lihat Butiran", "Now on sale": "Tempahan dibuka", "Match date to be confirmed": "Tarikh perlawanan belum ditetapkan", From: "Bermula dari", "Book Tickets Now": "Tempah Tiket Sekarang", "Coming Soon": "Akan Dibuka", "Sold Out": "Habis Dijual", Finished: "Tamat",
  "Verify OTP": "Sahkan OTP", "A code was sent to": "Kod telah dihantar ke", "OTP Code": "Kod OTP", "Verifying...": "Sedang mengesahkan...", "Verify and Show All Bookings": "Sahkan dan Paparkan Semua Tempahan", "Use Another Phone Number / Resend Code": "Gunakan Nombor Telefon Lain / Hantar Semula Kod", "Booking Phone Number": "Nombor Telefon Tempahan", "Sending code...": "Sedang menghantar kod...", "Send OTP": "Hantar OTP", Found: "Ditemui", tickets: "tiket", "Match tickets": "Tiket perlawanan", "Season passes": "Pas musim", "Search Another Number": "Cari Nombor Lain", "No bookings were found for this phone number": "Tiada tempahan ditemui untuk nombor telefon ini", "No match tickets found": "Tiada tiket perlawanan ditemui", Quantity: "Kuantiti", "Proceed to Payment": "Teruskan ke Pembayaran", "Open E-ticket": "Buka E-tiket", "Season Passes": "Pas Musim", passes: "pas", "No season passes found": "Tiada pas musim ditemui", "Season Pass": "Pas Musim", "Purchased on": "Dibeli pada", "Open Season Pass Barcode": "Buka Kod Bar Pas Musim",
};

export function localize(locale: Locale, th: string, en: string, ms = en): string {
  if (locale === "ms") return ms === en ? (msTranslations[en] ?? en) : ms;
  return locale === "en" ? en : th;
}

export function intlLocale(locale: Locale): "th-TH" | "en-US" | "ms-MY" {
  if (locale === "ms") return "ms-MY";
  return locale === "en" ? "en-US" : "th-TH";
}
